---
resources:
  - name: gitlab
    type: git
    source:
      uri: https://git.cto.ai/platform-solutions/ops/gitlab
      branch: feat/port-commands
      username: "tim@cto.ai"
      password: ((GITLAB_TOKEN))

  - name: 1h-timer
    type: time
    source: { interval: 60m }
jobs:
  - name: op-gitlab-e2e
    public: true
    plan:
      - get: 1h-timer
        trigger: true
      - get: gitlab
      - task: op-gitlab-e2e
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: node, tag: latest }
          inputs:
            - name: gitlab
          run:
            path: gitlab/op-gitlab-e2e.sh
          params:
            MAC_STADIUM_PASS: ((MAC_STADIUM_PASS))
            # SSH_PRIVATE_KEY: ((SSH_PRIVATE_KEY))
